import { AdminLayout } from "@/components/AdminLayout";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Download, GripVertical, ImagePlus, Link as LinkIcon, Trash2, Upload } from "lucide-react";
import { useRef, useState } from "react";

const products = [{ id: 1, name: "T-Shirt Premium Bleu" }, { id: 2, name: "Crème Hydratante Luxe" }, { id: 3, name: "Sac à Main Élégant" }, { id: 4, name: "Montre Classique" }, { id: 5, name: "Parfum Premium" }, { id: 6, name: "Ceinture Cuir" }, { id: 7, name: "Jeans Slim Fit" }, { id: 8, name: "Robe Soirée" }, { id: 9, name: "Peluche Douce" }, { id: 10, name: "Coffret Cadeau Luxe" }, { id: 11, name: "Chaussures Confort" }, { id: 12, name: "Accessoire quotidien" }];

export default function AdminMedia() {
  const [url, setUrl] = useState(""); const [altText, setAltText] = useState(""); const [selectedProduct, setSelectedProduct] = useState(1); const [dragged, setDragged] = useState<number | null>(null); const fileRef = useRef<HTMLInputElement>(null); const utils = trpc.useUtils();
  const media = trpc.content.media.list.useQuery(); const productMedia = trpc.content.media.byProduct.useQuery({ productId: selectedProduct });
  const addUrl = trpc.content.media.addUrl.useMutation({ onSuccess: () => { setUrl(""); setAltText(""); utils.content.media.list.invalidate(); } });
  const upload = trpc.content.media.upload.useMutation({ onSuccess: () => utils.content.media.list.invalidate() });
  const attach = trpc.content.media.attachToProduct.useMutation({ onSuccess: () => utils.content.media.byProduct.invalidate({ productId: selectedProduct }) });
  const reorder = trpc.content.media.reorderProduct.useMutation({ onSuccess: () => utils.content.media.byProduct.invalidate({ productId: selectedProduct }) });
  const remove = trpc.content.media.remove.useMutation({ onSuccess: () => { utils.content.media.list.invalidate(); utils.content.media.byProduct.invalidate({ productId: selectedProduct }); } });
  const handleFile = async (file?: File) => { if (!file || !file.type.startsWith("image/")) return; const base64 = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.onerror = reject; reader.readAsDataURL(file); }); upload.mutate({ filename: file.name, mimeType: file.type as "image/jpeg" | "image/png" | "image/webp" | "image/avif", base64, altText: file.name }); };
  const ordered = productMedia.data ?? [];
  const drop = (target: number) => { if (dragged === null || dragged === target) return; const next = [...ordered]; const from = next.findIndex((item) => item.media.id === dragged); const to = next.findIndex((item) => item.media.id === target); const [item] = next.splice(from, 1); next.splice(to, 0, item); setDragged(null); reorder.mutate({ productId: selectedProduct, mediaIds: next.map((entry) => entry.media.id) }); };
  return <AdminLayout><div className="space-y-6"><div><h1 className="font-display text-4xl text-[#211e1b]">Médiathèque</h1><p className="mt-2 text-[#6d6259]">Ajoutez des visuels et composez le carrousel de chaque fiche produit.</p></div>
    <div className="grid gap-5 lg:grid-cols-2"><Card className="rounded-3xl border-[#ded5ca] bg-[#fbf9f5] p-5"><div className="mb-4 flex items-center gap-2 font-semibold"><LinkIcon size={18} className="text-[#b65f3f]" /> Ajouter par URL</div><input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://..." className="mb-3 w-full rounded-xl border border-[#d5cec4] bg-white px-3 py-2" /><input value={altText} onChange={(e) => setAltText(e.target.value)} placeholder="Texte alternatif" className="mb-4 w-full rounded-xl border border-[#d5cec4] bg-white px-3 py-2" /><Button disabled={!url || addUrl.isPending} onClick={() => addUrl.mutate({ url, altText })} className="rounded-full bg-[#211e1b]">Ajouter l’image</Button></Card><Card className="rounded-3xl border-[#ded5ca] bg-[#fbf9f5] p-5"><div className="mb-4 flex items-center gap-2 font-semibold"><Upload size={18} className="text-[#b65f3f]" /> Télécharger un fichier</div><p className="mb-4 text-sm text-[#6d6259]">JPEG, PNG, WebP ou AVIF. Stockage durable hors du projet.</p><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp,image/avif" hidden onChange={(e) => handleFile(e.target.files?.[0])} /><Button disabled={upload.isPending} onClick={() => fileRef.current?.click()} className="rounded-full bg-[#b65f3f]">{upload.isPending ? "Téléchargement…" : "Choisir une image"}</Button></Card></div>
    <Card className="rounded-3xl border-[#ded5ca] bg-[#fbf9f5] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-display text-2xl">Carrousel produit</h2><p className="text-sm text-[#6d6259]">Glissez les vignettes pour enregistrer leur ordre d’affichage.</p></div><select value={selectedProduct} onChange={(e) => setSelectedProduct(Number(e.target.value))} className="rounded-xl border border-[#d5cec4] bg-white px-3 py-2">{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{ordered.map(({ media: item }) => <div key={item.id} draggable tabIndex={0} onDragStart={() => setDragged(item.id)} onDragOver={(e) => e.preventDefault()} onDrop={() => drop(item.id)} onKeyDown={(event) => { const position = ordered.findIndex((entry) => entry.media.id === item.id); const nextPosition = event.key === "ArrowLeft" || event.key === "ArrowUp" ? position - 1 : event.key === "ArrowRight" || event.key === "ArrowDown" ? position + 1 : position; if (nextPosition !== position && nextPosition >= 0 && nextPosition < ordered.length) { setDragged(item.id); drop(ordered[nextPosition].media.id); } }} className="group relative cursor-grab overflow-hidden rounded-2xl border border-[#ded5ca] bg-white active:cursor-grabbing"><img src={item.url} alt={item.altText ?? item.filename ?? "Image produit"} width="240" height="240" className="aspect-square w-full object-cover" /><span className="absolute left-2 top-2 rounded-full bg-[#211e1b]/80 p-1 text-white"><GripVertical size={14} /></span><span className="block truncate px-2 py-2 text-xs text-[#6d6259]">#{ordered.findIndex((entry) => entry.media.id === item.id) + 1} · {item.filename ?? "Image"}</span></div>)}</div>{!ordered.length && <p className="mt-5 rounded-2xl border border-dashed border-[#d5cec4] p-6 text-center text-sm text-[#6d6259]">Aucune image associée à ce produit.</p>}</Card>
    <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{(media.data ?? []).map((item) => <Card key={item.id} className="group overflow-hidden rounded-2xl border-[#ded5ca] bg-[#fbf9f5]"><div className="aspect-square bg-[#eee8df]"><img src={item.url} alt={item.altText ?? item.filename ?? "Image média"} className="h-full w-full object-cover transition duration-300 group-hover:scale-105" /></div><div className="p-3"><p className="truncate text-xs text-[#6d6259]">{item.filename ?? item.url}</p><div className="mt-3 grid grid-cols-3 gap-2"><Button onClick={() => attach.mutate({ productId: selectedProduct, mediaId: item.id, sortOrder: ordered.length })} className="col-span-2 rounded-full bg-[#211e1b] text-xs">Associer au produit</Button><a href={item.url} download={item.filename ?? true} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center rounded-full border border-[#d5cec4]"><Download size={14} /></a></div><button onClick={() => remove.mutate({ id: item.id })} className="mt-2 inline-flex items-center gap-1 text-xs text-[#b65f3f]"><Trash2 size={13} /> Supprimer</button></div></Card>)}</div>{!media.isLoading && !(media.data?.length) && <div className="rounded-2xl border border-dashed border-[#d5cec4] p-10 text-center text-[#6d6259]"><ImagePlus className="mx-auto mb-3" />Votre médiathèque est vide.</div>}</div></AdminLayout>;
}
